version: 1.0.{build}
image: Visual Studio 2017
environment:
  AWS_ACCESS_KEY_ID:
    secure: kDqp6sG9BKz2GSKdVeS1VUy/f7b/17ooP3n5tqSTY3E=
  AWS_SECRET_ACCESS_KEY:
    secure: 9LBGCZuz7N9tlIxDQFYa33OOeM6rMG5tY3UzroniBLq4lvOYbFbh0T97sjuGM5WO
build_script:
- ps: |-
    pip install --upgrade awscli
    Write-Host "Deploy version ${env:appveyor_build_number} to ${env:environment}"
    $env:build_number = $env:appveyor_build_number
    $taskdefn = Get-Content dockertest-task-definition.json
    $taskdefn = [Regex]::Replace($taskdefn, "{{(\w+)}}", { [environment]::GetEnvironmentVariable($args[0].Groups[1]) })
    Set-Content dockertest-task-definition.json $taskdefn
    aws ecs register-task-definition --region eu-west-1 --cli-input-json file://dockertest-task-definition.json
    $services = aws ecs describe-services --region eu-west-1 --cluster windows --service dockertest | ConvertFrom-Json
    if ($services.services.length -gt 0 -And $services.services[0].status -eq "ACTIVE") {
      aws ecs update-service --region eu-west-1 --cluster windows --service dockertest --task-definition dockertest-$env:environment
    } else {
      aws ecs create-service --region eu-west-1 --cli-input-json file://dockertest-service.json
    }
